import type { ProviderConfig } from '../types';

export const PROVIDERS: ProviderConfig[] = [
  {
    name: 'openrouter',
    type: 'gateway',
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKey: process.env.OPENROUTER_API_KEY,
    supportsScraping: true,
    priority: 1,
    freeTier: false,
  },
  {
    name: 'google',
    type: 'provider',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    apiKey: process.env.GOOGLE_API_KEY,
    supportsScraping: false,
    priority: 2,
    freeTier: true,
  },
  {
    name: 'mistral',
    type: 'provider',
    baseUrl: 'https://api.mistral.ai/v1',
    apiKey: process.env.MISTRAL_API_KEY,
    supportsScraping: false,
    priority: 3,
    freeTier: true,
  },
  {
    name: 'together',
    type: 'gateway',
    baseUrl: 'https://api.together.xyz/v1',
    apiKey: process.env.TOGETHER_API_KEY,
    supportsScraping: false,
    priority: 4,
    freeTier: true,
  },
  {
    name: 'cohere',
    type: 'provider',
    baseUrl: 'https://api.cohere.ai/v1',
    apiKey: process.env.COHERE_API_KEY,
    supportsScraping: false,
    priority: 5,
    freeTier: true,
  },
  {
    name: 'anthropic',
    type: 'provider',
    baseUrl: 'https://api.anthropic.com/v1',
    apiKey: process.env.ANTHROPIC_API_KEY,
    supportsScraping: false,
    priority: 6,
    freeTier: false,
  },
  {
    name: 'perplexity',
    type: 'gateway',
    baseUrl: 'https://api.perplexity.ai',
    apiKey: process.env.PERPLEXITY_API_KEY,
    supportsScraping: false,
    priority: 7,
    freeTier: false,
  },
  {
    name: 'kilo',
    type: 'gateway',
    baseUrl: 'https://kilo.ai',
    apiKey: process.env.KILO_API_KEY,
    supportsScraping: true,
    priority: 8,
    freeTier: false,
  },
  {
    name: 'groq',
    type: 'gateway',
    baseUrl: 'https://api.groq.com/openai/v1',
    apiKey: process.env.GROQ_API_KEY,
    supportsScraping: true,
    priority: 9,
    freeTier: false,
  },
  {
    name: 'ollama',
    type: 'provider',
    baseUrl: 'http://localhost:11434',
    apiKey: undefined,
    supportsScraping: false,
    priority: 10,
    freeTier: true,
  },
  {
    name: 'huggingface',
    type: 'provider',
    baseUrl: 'https://huggingface.co',
    apiKey: process.env.HUGGINGFACE_API_KEY,
    supportsScraping: true,
    priority: 11,
    freeTier: false,
  },
];
